### ISSUE TITLE
Add Leetcode Questions

### ISSUE THREAD

**Issue by unikdahal** [unikdahal/All-Leetcode-Questions#1]
Add leetcode questions along with their solutions in a folder

**Comment by Shivashish-rwt** [comment]
I can work on this. Please assign this to me.

**Comment by kunalranjan19** [comment]
hey, can I work on this or do I need to open a new issue. I already had a repo in which I posted some of the solutions would that be okay to add the same

**Comment by unikdahal** [comment]
Open a new issue i will assign you

**Comment by kunalranjan19** [comment]
okay
