### ISSUE TITLE
My Leetcode Questions

### ISSUE THREAD

**Issue by kunalranjan19** [unikdahal/All-Leetcode-Questions#5]
Hey i want to add my Leetcode solutions

**Comment by kunalranjan19** [comment]
hey @unikdahal even after my PR is merged why did the hactober site progress says 0 .I am participating for the first time can you help:)

**Comment by kunalranjan19** [comment]
bro i guess you have to add hactoberfest accepted label in the PR

**Comment by unikdahal** [comment]
It will get updated after some time in the site
